guard against broken upstream
remote.origin.url may not be working so we want to catch the case where
we couldn't read from upstream. Gracefully assume there are no changes
to pull as we couldn't read anything anyway.

diff --git a/bin/git_has_remote_updates b/bin/git_has_remote_updates
--- a/bin/git_has_remote_updates
+++ b/bin/git_has_remote_updates
@@ -37,8 +37,14 @@ then
   exit 1
 fi
 
-remote_sha=`git ls-remote origin -h refs/heads/${branch} |
+remote_sha=`git ls-remote origin -h refs/heads/${branch} 2>/dev/null |
   awk '{print $1;exit}'`
+
+if [ -z "$remote_sha" ]
+then
+  test -n "${verbose}" && echo "could not read from upstream"
+  exit 1
+fi
 
 if git rev-list origin/${branch} | grep -q "${remote_sha}"
 then
